// <auto-generated />
using System;
using Ecommerencesite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerencesite.Migrations
{
    [DbContext(typeof(Ecommerecewebstedatabase))]
    [Migration("20251206062338_newmigrationupdate")]
    partial class newmigrationupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerencesite.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseModelstatusCode")
                        .HasColumnType("int");

                    b.Property<decimal>("Totalprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponseModelstatusCode");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Medicine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMAGEURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseModelstatusCode")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("ResponseModelstatusCode");

                    b.ToTable("medicines");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderStatus")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ordertotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ResponseModelstatusCode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ResponseModelstatusCode");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Ecommerencesite.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseModelstatusCode")
                        .HasColumnType("int");

                    b.Property<decimal>("Totalprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ResponseModelstatusCode");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("Ecommerencesite.Model.ResponseModel", b =>
                {
                    b.Property<int>("statusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusCode"));

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.Property<int>("medicineid")
                        .HasColumnType("int");

                    b.Property<int>("orderItemId")
                        .HasColumnType("int");

                    b.Property<int>("orderid")
                        .HasColumnType("int");

                    b.Property<string>("responseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userMedicineid")
                        .HasColumnType("int");

                    b.HasKey("statusCode");

                    b.HasIndex("cartId");

                    b.HasIndex("medicineid");

                    b.HasIndex("orderItemId");

                    b.HasIndex("orderid");

                    b.HasIndex("userMedicineid");

                    b.ToTable("responseModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.UserMedicine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseModelstatusCode")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ResponseModelstatusCode");

                    b.ToTable("userMedicines");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Cart", b =>
                {
                    b.HasOne("Ecommerencesite.Model.ResponseModel", null)
                        .WithMany("LSTcarts")
                        .HasForeignKey("ResponseModelstatusCode");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Medicine", b =>
                {
                    b.HasOne("Ecommerencesite.Model.ResponseModel", null)
                        .WithMany("LSTmedicines")
                        .HasForeignKey("ResponseModelstatusCode");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Order", b =>
                {
                    b.HasOne("Ecommerencesite.Model.ResponseModel", null)
                        .WithMany("LSTorders")
                        .HasForeignKey("ResponseModelstatusCode");
                });

            modelBuilder.Entity("Ecommerencesite.Model.OrderItem", b =>
                {
                    b.HasOne("Ecommerencesite.Model.ResponseModel", null)
                        .WithMany("LSTorderItems")
                        .HasForeignKey("ResponseModelstatusCode");
                });

            modelBuilder.Entity("Ecommerencesite.Model.ResponseModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.Cart", "cart")
                        .WithMany()
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerencesite.Model.Medicine", "medicine")
                        .WithMany()
                        .HasForeignKey("medicineid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerencesite.Model.OrderItem", "orderItem")
                        .WithMany()
                        .HasForeignKey("orderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerencesite.Model.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerencesite.Model.UserMedicine", "userMedicine")
                        .WithMany()
                        .HasForeignKey("userMedicineid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("medicine");

                    b.Navigation("order");

                    b.Navigation("orderItem");

                    b.Navigation("userMedicine");
                });

            modelBuilder.Entity("Ecommerencesite.Model.UserMedicine", b =>
                {
                    b.HasOne("Ecommerencesite.Model.ResponseModel", null)
                        .WithMany("LSTuserMedicines")
                        .HasForeignKey("ResponseModelstatusCode");
                });

            modelBuilder.Entity("Ecommerencesite.Model.ResponseModel", b =>
                {
                    b.Navigation("LSTcarts");

                    b.Navigation("LSTmedicines");

                    b.Navigation("LSTorderItems");

                    b.Navigation("LSTorders");

                    b.Navigation("LSTuserMedicines");
                });
#pragma warning restore 612, 618
        }
    }
}
