// <auto-generated />
using System;
using Ecommerencesite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerencesite.Migrations
{
    [DbContext(typeof(Ecommerecewebstedatabase))]
    [Migration("20260911073231_newddd")]
    partial class newddd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerencesite.Model.AdminREGMODEL", b =>
                {
                    b.Property<int>("ADMINid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ADMINid"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<decimal?>("Fund")
                        .HasColumnType("numeric");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("ADMINid");

                    b.ToTable("adminREGMODELSs");
                });

            modelBuilder.Entity("Ecommerencesite.Model.AdminTypeModel", b =>
                {
                    b.Property<int>("Admintypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Admintypeid"));

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("Admintypeid");

                    b.ToTable("admintypess");
                });

            modelBuilder.Entity("Ecommerencesite.Model.AssignRaiseTicketModel", b =>
                {
                    b.Property<int>("AssignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignId"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.HasKey("AssignId");

                    b.ToTable("AssignRaiseTicket");
                });

            modelBuilder.Entity("Ecommerencesite.Model.BankRefundableAmountModel", b =>
                {
                    b.Property<int>("BankRefundableAmountid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankRefundableAmountid"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankBranchAddress")
                        .HasColumnType("text");

                    b.Property<string>("BankBranchCity")
                        .HasColumnType("text");

                    b.Property<string>("BankBranchName")
                        .HasColumnType("text");

                    b.Property<string>("BankBranchState")
                        .HasColumnType("text");

                    b.Property<string>("BankIFSCCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("BankRefundableAmount")
                        .HasColumnType("numeric");

                    b.Property<bool?>("BankRefundableAmountStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Bank_CustomerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BankRefundableAmountid");

                    b.ToTable("BankRefundableAmountModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.CandidateApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentCTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("ExpectedCTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("NoticePeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("candidateapplicationmodules");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("cartss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.CityMasterModel", b =>
                {
                    b.Property<int>("cityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cityid"));

                    b.Property<string>("Cityname")
                        .HasColumnType("text");

                    b.Property<string>("statename")
                        .HasColumnType("text");

                    b.HasKey("cityid");

                    b.ToTable("cityMasterModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.CustomerAccountantAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByAccountant")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<decimal?>("OpeningBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("customerAccountantAccounts");
                });

            modelBuilder.Entity("Ecommerencesite.Model.CustomerAddMedicineModel", b =>
                {
                    b.Property<int>("CustomerAddMedicineModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerAddMedicineModelId"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("MedicineDescription")
                        .HasColumnType("text");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.HasKey("CustomerAddMedicineModelId");

                    b.ToTable("customerAddMedicineModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.CustomerHelpIssueModel", b =>
                {
                    b.Property<int>("customerhelpissueid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customerhelpissueid"));

                    b.Property<string>("CustomerHelpEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerHelpMessage")
                        .HasColumnType("text");

                    b.Property<string>("CustomerHelpName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerHelpStatus")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.HasKey("customerhelpissueid");

                    b.ToTable("customerHelpIssueModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.AvailableTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("AvailableTestModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.BloodGlucoseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("BloodGlucoseDatas");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.BloodPressureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("BloodPressureDatas");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("SettingsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("SettingsId");

                    b.ToTable("DashboardDataModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.HealthHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("DiagnosedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("HealthHistoryModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.Help_SupportTicketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("SupportTicketModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.HistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("HistoryModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.MedicationTrackerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("MedicationTrackerModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.MonthlyProgressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("MonthlyProgressModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.PrescriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("DateIssued")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("PrescriptionModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.TestReportModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportFileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("TestReportModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.UserSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserSettingsModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.WeightProgressData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardDataModelid")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DashboardDataModelid");

                    b.ToTable("WeightProgressDatas");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DeliveryAssigntoModel", b =>
                {
                    b.Property<int>("DeliveryAssgintoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryAssgintoId"));

                    b.Property<string>("DeliveryPerdsonType")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPersonName")
                        .HasColumnType("text");

                    b.HasKey("DeliveryAssgintoId");

                    b.ToTable("deliveryAssigntoModells");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DoctorAssigntoPatientMOdel", b =>
                {
                    b.Property<int>("DoctorAssigntoPatientod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DoctorAssigntoPatientod"));

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<string>("DoctorType")
                        .HasColumnType("text");

                    b.HasKey("DoctorAssigntoPatientod");

                    b.ToTable("doctorAssigntoPatientMOdels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.FeedbackCusotmerModel", b =>
                {
                    b.Property<int>("Freedbackcustomerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Freedbackcustomerid"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("starStatus")
                        .HasColumnType("text");

                    b.HasKey("Freedbackcustomerid");

                    b.ToTable("feedbackCusotmerModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.HealthReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodGlucose")
                        .HasColumnType("integer");

                    b.Property<int>("Diastolic")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Systolic")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("HealthReports");
                });

            modelBuilder.Entity("Ecommerencesite.Model.IssueCategorymasterModel", b =>
                {
                    b.Property<int>("issuecategorymasterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("issuecategorymasterid"));

                    b.Property<string>("IssueCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("issuecategorymasterid");

                    b.ToTable("issuecategorymasterModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.LivenessCheckRequestModel", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<int>("BlinkCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrameData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.ToTable("livenessrequestcheckmodel");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Medicationgetmodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<bool?>("IsMissed")
                        .HasColumnType("boolean");

                    b.Property<string>("MealTiming")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("NextDose")
                        .HasColumnType("interval");

                    b.Property<bool?>("Taken")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Medicine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("ItemMedicine")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MedicinesType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ONlyMgMEDICINE")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("STATUS")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("medicinesss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.MedicineChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicineChats");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("EstimatedTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Ordertotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("orderss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Totalprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("orderItemss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.PatientDetailsModel", b =>
                {
                    b.Property<int>("patientDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("patientDetailsId"));

                    b.Property<string>("PatientName")
                        .HasColumnType("text");

                    b.Property<string>("PatientReason")
                        .HasColumnType("text");

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.HasKey("patientDetailsId");

                    b.ToTable("patientDetailsModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Patient_CustomerModel", b =>
                {
                    b.Property<int>("Patient_CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Patient_CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedDeliveryPerson")
                        .HasColumnType("text");

                    b.Property<string>("AssignedDoctor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCity")
                        .HasColumnType("text");

                    b.Property<string>("CustomerState")
                        .HasColumnType("text");

                    b.Property<string>("CustomerZipCode")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Patient_CustomerId");

                    b.ToTable("patient_CustomerModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.QRCashCodeModels", b =>
                {
                    b.Property<int>("QRcashcodeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QRcashcodeid"));

                    b.Property<string>("QRCodeImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QRcashcodeid");

                    b.ToTable("qRCashCodeModelss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.StateNameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StateName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stateNameModels");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Team_HiringModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExperienceRequired")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NoOfOpenings")
                        .HasColumnType("integer");

                    b.Property<decimal>("OfferedCTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("team_hiringmodules");
                });

            modelBuilder.Entity("Ecommerencesite.Model.UserMedicine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Fund")
                        .HasColumnType("numeric");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userMediciness");
                });

            modelBuilder.Entity("Ecommerencesite.Model.bankdetailsModles", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("CVV")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .HasColumnType("text");

                    b.Property<string>("CardholderName")
                        .HasColumnType("text");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("text");

                    b.HasKey("BankId");

                    b.ToTable("bankdetailsModless");
                });

            modelBuilder.Entity("Ecommerencesite.Model.bankselectmodels", b =>
                {
                    b.Property<int>("bankselectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("bankselectid"));

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.HasKey("bankselectid");

                    b.ToTable("bankselectmodelss");
                });

            modelBuilder.Entity("Ecommerencesite.Model.choice_MultipleLanguageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("choicemultiplelanguagemodel");
                });

            modelBuilder.Entity("Ecommerencesite.Model.deliverypartnermodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("deliverypartnermodels");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.CustomerTicketRaiseModel", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("Attachment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentOption")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueCategory")
                        .HasColumnType("text");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionRemark")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TicketId");

                    b.ToTable("CustomerTicketRaise");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.AvailableTestModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("AvailableTests")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.BloodGlucoseData", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("BloodGlucose")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.BloodPressureData", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("BloodPressure")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.CartItem", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("CartMedicines")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.UserSettingsModel", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.HealthHistoryModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("HealthHistories")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.Help_SupportTicketModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.HistoryModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("HistoryRecords")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.MedicationTrackerModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("MedicationTrackers")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.MonthlyProgressModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("MonthlyProgresses")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.PrescriptionModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.TestReportModel", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("TestReports")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.WeightProgressData", b =>
                {
                    b.HasOne("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", null)
                        .WithMany("WeightProgress")
                        .HasForeignKey("DashboardDataModelid");
                });

            modelBuilder.Entity("Ecommerencesite.Model.OrderItem", b =>
                {
                    b.HasOne("Ecommerencesite.Model.Order", "Order")
                        .WithMany("OrderItemss")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerencesite.Model.DASHBOARDS.DashboardDataModel", b =>
                {
                    b.Navigation("AvailableTests");

                    b.Navigation("BloodGlucose");

                    b.Navigation("BloodPressure");

                    b.Navigation("CartMedicines");

                    b.Navigation("HealthHistories");

                    b.Navigation("HistoryRecords");

                    b.Navigation("MedicationTrackers");

                    b.Navigation("MonthlyProgresses");

                    b.Navigation("Prescriptions");

                    b.Navigation("SupportTickets");

                    b.Navigation("TestReports");

                    b.Navigation("WeightProgress");
                });

            modelBuilder.Entity("Ecommerencesite.Model.Order", b =>
                {
                    b.Navigation("OrderItemss");
                });
#pragma warning restore 612, 618
        }
    }
}
